<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>JustBedwars.GTK</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="GirCore.Gtk-4.0" Version="0.7.0" />
    <PackageReference Include="GirCore.Adw-1" Version="0.7.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JustBedwars.Core\JustBedwars.Core.csproj" />
  </ItemGroup>
</Project>