; Script generated by the Inno Setup Script Wizard.

#define MyAppName "JustBedwars"
#define MyAppVersion "1.6.3"
#define MyAppPublisher "fex2000"
#define MyAppURL "https://fex2000.github.io/JustBedwars"
#define MyAppExeName "JustBedwars.exe"
#define MyAppId "{72E500CC-2A2D-4DE6-8EF7-391DB4CC78E3}"

[Setup]
AppId={{#MyAppId}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
ArchitecturesAllowed=x64compatible
PrivilegesRequired=admin
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
OutputDir=D:\Code\JustBedwars\Setup
OutputBaseFilename=install
SetupIconFile=D:\Code\JustBedwars\Assets\Icon.ico
SolidCompression=yes
WizardStyle=modern windows11
WizardSizePercent=120,100
CloseApplications=force

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
Source: "D:\Code\JustBedwars\Setup\Source\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "D:\Code\JustBedwars\Setup\Source\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"

[Run]
; Show Fresh Install
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent; Check: IsFreshInstall

; Set to Upgrade Mode
Filename: "{app}\{#MyAppExeName}"; Flags: nowait; Check: IsUpgradeInstall

[Code]
// --- IMPORTS & CONSTANTS FOR PAGE SKIPPING ---
function PostMessage(hWnd: HWND; Msg: UINT; wParam: Longint; lParam: Longint): BOOL;
  external 'PostMessageW@user32.dll stdcall';

const
  BN_CLICKED = 0;
  WM_COMMAND = $0111;
  CN_BASE = $BC00;
  CN_COMMAND = CN_BASE + WM_COMMAND;

var
  isUpgrade: Boolean;

// --- INITIALIZE ---
function InitializeSetup(): Boolean;
var
  sUnInstPath: String;
  sRegKey: String;
  foundHKLM, foundHKCU, foundHKLM32: Boolean;
begin
  // Build the registry key string.
  sRegKey := 'Software\Microsoft\Windows\CurrentVersion\Uninstall\{#MyAppId}_is1';

  // 1. Check Native HKLM - Current Architecture Installs
  foundHKLM := RegQueryStringValue(HKLM, sRegKey, 'UninstallString', sUnInstPath);

  // 2. Check HKCU (Current User)
  foundHKCU := RegQueryStringValue(HKCU, sRegKey, 'UninstallString', sUnInstPath);

  // 3. Check HKLM-32 (WOW6432Node) - 32 Bit installs
  foundHKLM32 := RegQueryStringValue(HKLM32, sRegKey, 'UninstallString', sUnInstPath);

  isUpgrade := foundHKLM or foundHKCU or foundHKLM32;
  
  Result := True;
end;

// --- HELPER FUNCTIONS ---
function IsUpgradeInstall: Boolean;
begin
  Result := isUpgrade;
end;

function IsFreshInstall: Boolean;
begin
  Result := not isUpgrade;
end;

// Force Close
procedure ForceCloseApp;
var
  ResultCode: Integer;
begin
  Exec('taskkill.exe', '/F /IM "{#MyAppExeName}" /T', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  // Fallback
  if ResultCode <> 0 then
  begin
    Exec('wmic.exe', 'process where "name=''#MyAppExeName''" delete', '', SW_HIDE, ewWaitUntilTerminated, ResultCode);
  end;
end;

// --- PAGE SKIPPING ---
function ShouldSkipPage(PageID: Integer): Boolean;
begin
  Result := False;
  if isUpgrade then begin
    // 1. Skip Welcome Page
    if PageID = wpWelcome then Result := True;
    
    // 2. Skip Directory Select
    if PageID = wpSelectDir then Result := True;
    
    // 3. Skip Ready Page (If possible)
    if PageID = wpReady then Result := True;
  end;
end;

procedure CurPageChanged(CurPageID: Integer);
var
  Param: Longint;
begin
  if isUpgrade then
  begin
    // Skip Welcome and SelectDir
    if (CurPageID = wpWelcome) or (CurPageID = wpSelectDir) then
    begin
      WizardForm.NextButton.OnClick(WizardForm);
    end;
    
    // Skip Ready Page
    if CurPageID = wpReady then
    begin
       Param := 0 or BN_CLICKED shl 16;
       PostMessage(WizardForm.NextButton.Handle, CN_COMMAND, Param, 0);
    end;

    // Auto Finish on Update
    if (CurPageID = wpFinished) then
    begin
      WizardForm.NextButton.OnClick(WizardForm);
    end;
  end;
end;

// --- CLEANUP ---
procedure CurStepChanged(CurStep: TSetupStep);
begin
  if (CurStep = ssInstall) then
  begin
    if DirExists(ExpandConstant('{app}')) then
    begin
      DelTree(ExpandConstant('{app}\*'), False, True, True);
    end;
  end;
end;